### PR TITLE
:rocket: :bookmark: “In individuals, insanity is rare; but in groups, parties, nations, PSW firms and epochs, it is the rule.”

### PR DESCRIPTION
**Pull request by jelena-vlajkov**

### CODE REVIEW

**Comment by danica1998** [comment]
Good job, nice one 👌

**Comment by kaiser18** [comment]
Good job mates!

**Review by danica1998 — APPROVED** [review]

**Review by kaiser18 — APPROVED** [review]
:rocket: :rocket: :rocket:

**Review by oakenknight — COMMENTED** [review]
ide ⛽ na 🔝

**Review by oakenknight — APPROVED** [review]
♿

**Pull request merged**
