### PR TITLE
Graphic editor

### PR DESCRIPTION
**Pull request by cyberpoetry17**

### CODE REVIEW

**Comment by cyberpoetry17** [comment]
merging graphic_editor branch into develop branch

**Comment by jelena-vlajkov** [comment]
[Review Graphic Editor code.](https://trello.com/c/6sGY6lb6/24-review-graphic-editor-code)

**Review by oakenknight — DISMISSED** [review]

**Review by jelena-vlajkov — CHANGES_REQUESTED** [review]
Try to make width and height of main window adaptable for different resolutions.

**Review by st3fan7 — COMMENTED** [review]
It's all right.

**Review by oakenknight — CHANGES_REQUESTED** [review]
What Jelena said before

**Pull request merged**
